title: Min Uddannelsesportefølje
description: Portfolio: Marlen Halvorsen
theme: minima          # bruger GitHub Pages’ indbyggede tema
timezone: Europe/Copenhagen
future: true

url: "https://maha63312.github.io"
baseurl: ""

markdown: kramdown

plugins:
  - jekyll-paginate
paginate: 10
paginate_path: "/page:num/"
